# Generated by Django 4.2 on 2023-04-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='genre',
            field=models.ManyToManyField(to='myapp.artist'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.DurationField(),
        ),
    ]
