# Generated by Django 4.2 on 2023-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_genres_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(to='myapp.songs'),
        ),
    ]
