# Generated by Django 4.2 on 2023-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='myapp.genres'),
        ),
    ]
