# Generated by Django 4.2 on 2023-04-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.artist'),
        ),
    ]
