# Generated by Django 4.2 on 2023-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_album_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='myapp.songs'),
        ),
    ]
